/** @type {import("tailwindcss").Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        cream: "#F7F9FC",
        surface: "#FFFFFF",
        "surface-alt": "#F1F5F9",
        "surface-warm": "#F8FAFC",
        purple: "#2563EB",
        "purple-soft": "#1D4ED8",
        "purple-light": "#DBEAFE",
        "purple-pale": "#93C5FD",
        peach: "#F4A261",
        "peach-light": "#FFF0E0",
        "peach-pale": "#FCD5A8",
        mint: "#5EC4A0",
        "mint-light": "#E0F7EE",
        "mint-pale": "#A7E8C9",
        rose: "#E8788A",
        "rose-light": "#FFE8EC",
        "rose-pale": "#F5B5C0",
        amber: "#E8B44A",
        "amber-light": "#FFF5DC",
        ink: "#1E293B",
        "ink-2": "#334155",
        "ink-3": "#94A3B8",
        "ink-4": "#CBD5E1",
        "ink-alt": "#0F172A",
        border: "#E8EDF3",
        "border-soft": "#E8EDF3",
        "mint-text": "#3A9B74",
        "peach-text": "#C47A30",
        "rose-text": "#A8445A",
        "amber-text": "#7A6318",
        "auth-purple": "#EFF6FF",
        "auth-peach": "#FFF7ED",
        "auth-mint": "#ECFDF5",
        "frame-bg": "#E2E8F0",
        "frame-mid": "#475569",
      },
      fontFamily: {
        sans: ["Inter", "-apple-system", "sans-serif"],
        "sans-medium": ["InterMedium", "-apple-system", "sans-serif"],
        "sans-semibold": ["InterSemiBold", "-apple-system", "sans-serif"],
        display: ["SpaceGrotesk", "sans-serif"],
        "display-semibold": ["SpaceGroteskSemiBold", "sans-serif"],
        "display-bold": ["SpaceGroteskBold", "sans-serif"],
        hand: ["Caveat", "cursive"],
      },
    },
  },
  plugins: [],
};
