/** @type {import("tailwindcss").Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        cream: "var(--cream)",
        surface: "var(--surface)",
        "surface-alt": "var(--surface-alt)",
        "surface-warm": "var(--surface-warm)",
        purple: "var(--purple)",
        "purple-soft": "var(--purple-soft)",
        "purple-light": "var(--purple-light)",
        "purple-pale": "var(--purple-pale)",
        peach: "var(--peach)",
        "peach-light": "var(--peach-light)",
        "peach-pale": "var(--peach-pale)",
        mint: "var(--mint)",
        "mint-light": "var(--mint-light)",
        "mint-pale": "var(--mint-pale)",
        rose: "var(--rose)",
        "rose-light": "var(--rose-light)",
        "rose-pale": "var(--rose-pale)",
        "rose-soft": "var(--rose-soft)",
        amber: "var(--amber)",
        "amber-light": "var(--amber-light)",
        ink: "var(--ink)",
        "ink-2": "var(--ink-2)",
        "ink-3": "var(--ink-3)",
        "ink-4": "var(--ink-4)",
        "ink-alt": "var(--ink-alt)",
        "ink-surface": "var(--ink-surface)",
        border: "var(--border)",
        "border-soft": "var(--border-soft)",
        "mint-text": "var(--mint-text)",
        "peach-text": "var(--peach-text)",
        "rose-text": "var(--rose-text)",
        "amber-text": "var(--amber-text)",
        "amber-dark": "var(--amber-dark)",
        "frame-bg": "var(--frame-bg)",
        "frame-mid": "var(--frame-mid)",
        "auth-purple": "var(--auth-purple)",
        "auth-peach": "var(--auth-peach)",
        "auth-mint": "var(--auth-mint)",
        "glass-bg": "var(--glass-bg)",
        "glass-heavy": "var(--glass-heavy)",
        "glass-border": "var(--glass-border)",
        "cream-alpha": "var(--cream-alpha)",
        "cream-alpha-95": "var(--cream-alpha-95)",
      },
      fontFamily: {
        sans: ["Inter", "-apple-system", "sans-serif"],
        "sans-medium": ["InterMedium", "-apple-system", "sans-serif"],
        "sans-semibold": ["InterSemiBold", "-apple-system", "sans-serif"],
        display: ["SpaceGrotesk", "sans-serif"],
        "display-semibold": ["SpaceGroteskSemiBold", "sans-serif"],
        "display-bold": ["SpaceGroteskBold", "sans-serif"],
        hand: ["Caveat", "cursive"],
      },
      boxShadow: {
        xs: "0 1px 2px rgba(0,0,0,0.04)",
        sm: "0 1px 3px rgba(0,0,0,0.06)",
        md: "0 4px 6px rgba(0,0,0,0.08)",
        lg: "0 10px 15px rgba(0,0,0,0.15)",
        xl: "0 20px 25px rgba(0,0,0,0.25)",
        "purple-glow": "0 0 0 3px var(--purple-glow)",
        "purple-intense": "0 4px 16px var(--purple-glow-intense)",
      },
      animation: {
        "slide-up": "slideUp 0.4s ease-out both",
        typing: "typingAnim 1.4s ease-in-out infinite",
      },
      keyframes: {
        slideUp: {
          "0%": { opacity: "0", transform: "translateY(12px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        typingAnim: {
          "0%, 60%, 100%": { transform: "translateY(0)", opacity: "0.4" },
          "30%": { transform: "translateY(-4px)", opacity: "1" },
        },
      },
    },
  },
  plugins: [],
};
